ifeval::["{lang}" == "en"]
== SUSE Software Components
In this section, the focus is on the SUSE components: SUSE Linux Enterprise Server (SLES), SUSE Enterprise Storage (SES), and the Repository Mirroring Tool (RMT).

SUSE Linux Enterprise Server::
A world class secure, open source server operating system, equally adept at powering physical, virtual, or cloud-based mission-critical workloads. SUSE Linux Enterprise Server {SLESVersion} further raises the bar in helping organizations to accelerate innovation, enhance system reliability, meet tough security requirements and adapt to new technologies.

Repository Mirroring Tool::
Allows enterprise customers to optimize the management of SUSE Linux Enterprise (and other products such as SUSE Enterprise Storage) software updates and subscription entitlements. It establishes a proxy system for SUSE Customer Center with repository and registration targets.

SUSE Enterprise Storage::
Provided as an product on top of SUSE Linux Enterprise Server, this intelligent software-defined storage solution, powered by Ceph technology with enterprise engineering and support from SUSE enables customers to transform enterprise infrastructure to reduce costs while providing unlimited scalability.
endif::[]
ifeval::["{lang}" == "zh_CN"]
endif::[]