== Introduction
The objective of this guide is to present a step-by-step guide on how to implement SUSE Enterprise Storage {SESVersion} on the {vendor} {vPlatform} platform. It is suggested that the document be read in its entirety, along with the supplemental appendix information before attempting the process.

The deployment presented in this guide aligns with architectural best practices and will support the implementation of all currently supported protocols as identified in the SUSE Enterprise Storage documentation.

Upon completion of the steps in this document, a working SUSE Enterprise Storage {SESVersion} cluster will be operational as described in the https://www.suse.com/documentation/ses-5/book_storage_admin/data/book_storage_admin.html[SUSE Enterprise Storage Deployment and Administration Guide].

== Target Audience
This reference architecture is targeted at administrators who deploy software defined storage solutions within their data centers and making the different storage services accessible to their own customer base. By following this document as well as those referenced herein, the administrator should have a full view of the SUSE Enterprise Storage architecture, deployment and administrative tasks, with a specific set of recommendations for deployment of the hardware and networking platform.

== Hardware & Software
The recommended architecture for SUSE Enterprise Storage on {vendor} {vPlatform} leverages {serverModelCount} models of {vendor} servers. The role and functionality of each type of system within the SUSE Enterprise Storage environment will be explained in more detail in the architectural overview section.

.Storage Nodes:
* {vendor} {OSDModel}
+
{OSDYESLink}

.{node2Roles}:
* {vendor} {node2Model}
+
{node2YESLink}

.Switches:
* {switchVendor} {switchModel} {switchSpeed}

.Software:
* SUSE Enterprise Storage {SESVersion}
* SUSE Linux Enterprise Server {SLESVersion}

TIP: Please note that limited use subscriptions are provided with SUSE Enterprise Storage as part of the subscription entitlement