ifeval::["{lang}" == "en"]
== Requirements
Enterprise storage systems require reliability, manageability, and serviceability. The legacy storage players have established a high threshold for each of these areas and now expect the software defined storage solutions to offer the same. Focusing on these areas helps SUSE make open source technology enterprise consumable. When combined with highly reliable and manageable hardware from {vendor}, the result is a solution that meets the customer's expectation.

=== Functional Requirements
A SUSE Enterprise Storage solution is:

* Simple to setup and deploy, within the documented guidelines of system hardware, networking and environmental prerequisites.
* Adaptable to the physical and logical constraints needed by the business, both initially and as needed over time for performance, security, and scalability concerns.
* Resilient to changes in physical infrastructure components, caused by failure or required maintenance.
* Capable of providing optimized object and block services to client access nodes, either directly or through gateway services.
endif::[]
ifeval::["{lang}" == "zh_CN"]
endif::[]